name: Flake8
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Build dev environment
        run: |
          pip install .[dev]
          sudo apt install shellcheck shfmt
      - name: Run Black formatter
        run: |
          black --check .
      - name: Run flake8 linter
        run: |
          flake8 .
      - name: Run isort to check imports
        run: |
          isort --check-only .
      - name: Run shfmt and shellcheck on the builder scripts
        run: |
          cd builder/tangos_db
          shfmt -w build_tangos.sh
          shellcheck -x build_tangos.sh
          cd ../volume_ic
          shfmt -w build.sh
          shellcheck -x build.sh
